# Generated by Django 5.0.6 on 2024-10-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='photo',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='Book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='Description',
            field=models.TextField(max_length=100),
        ),
    ]
