# Generated by Django 5.0.6 on 2024-10-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_book_photo_alter_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='boook'),
        ),
    ]
