# Generated by Django 5.0.6 on 2024-10-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0008_alter_depositmoney_amount_alter_depositmoney_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='Borrowing_Price',
            field=models.IntegerField(default=0),
        ),
    ]
