# Generated by Django 5.0.6 on 2024-10-27 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0012_alter_book_user_alter_borrowedbook_book_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BorrowedBook',
        ),
    ]
