# Generated by Django 5.0.6 on 2024-10-27 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0014_borrowedbook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BorrowedBook',
        ),
    ]
