# Generated by Django 5.0.6 on 2024-10-27 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0016_borrowedbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowedbook',
            old_name='borrowed_date',
            new_name='borrow_date',
        ),
    ]
